foodfun/Models/MetaData/Propertys.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace foodfun.Models
{

    [MetadataType(typeof(PropertysMetaData))]

    public partial class Propertys
    {
        private class PropertysMetaData
        {
            [Key]
            [Display(Name = "流水編號")]
            public int rowid { get; set; }


            [Required(ErrorMessage = "產品屬性編號不可空白")]
            [DisplayFormat(ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入產品屬性編號")]
            [Display(Name = "產品屬性編號")]

            public string property_no { get; set; }

            [Required(ErrorMessage = "產品屬性名稱不可空白")]
            [Display(Name = "產品屬性名稱")]

            public string property_name { get; set; }

            [Display(Name = "單項加價金額")]
            public Nullable<int> add_price { get; set; }


            [Required(ErrorMessage = "屬性等級不可空白")]
            [Display(Name = "屬性等級")]
            public string property_value { get; set; }


            [Display(Name = "備註")]
            public string remark { get; set; }
          
        }
    }
}

foodfun/Models/Propertys.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodfun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propertys
    {
        public int rowid { get; set; }
        public string property_no { get; set; }
        public string property_name { get; set; }
        public Nullable<int> add_price { get; set; }
        public string property_value { get; set; }
        public string remark { get; set; }
    }
}

foodfun/Areas/Admin/Controllers/PropertysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using foodfun.Models;

namespace foodfun.Areas.Admin.Controllers
{
    public class PropertysController : Controller
    {
        // GET: Admin/Propertys
        public ActionResult Index()
        {
            // return View(repo_product.ReadAll().OrderBy(m => m.mno));

            using (GoPASTAEntities db = new GoPASTAEntities())
            {
                return View(db.Propertys.OrderBy(m => m.rowid).ToList());

            }
        }

        public ActionResult Create()
        {
            using (GoPASTAEntities db = new GoPASTAEntities())
            {

                Propertys model = new Propertys();

                return View(model);

            }
        }

        [HttpPost]
        public ActionResult Create(Propertys model)
        {
            if (!ModelState.IsValid) return View(model);


            using (GoPASTAEntities db = new GoPASTAEntities())
            {
                db.Propertys.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "Admin")]
        public ActionResult Edit(int id)
        {
            using (GoPASTAEntities db = new GoPASTAEntities())
            {
                //if (id == 0)
                //{
                //    Categorys new_model = new Categorys();
                //    return View(new_model);
                //}
                var models = db.Propertys.Where(m => m.rowid == id).FirstOrDefault();
                return View(models);
            }
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "Admin")]
        public ActionResult Edit(Propertys model)
        {

            if (!ModelState.IsValid) return View(model);
            using (GoPASTAEntities db = new GoPASTAEntities())
            {
                // var data = db.Propertys.Where(m => m.property_no == model.property_no).FirstOrDefault();
                var data = db.Propertys.Where(m => m.rowid == model.rowid).FirstOrDefault();
                // data.rowid = model.rowid;
                data.property_no = model.property_no;
                data.property_name = model.property_name;
                data.add_price = model.add_price;
                data.property_value = model.property_value;
                data.remark = model.remark;

                db.SaveChanges();
                return RedirectToAction("Index");
            }

        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            using (GoPASTAEntities db = new GoPASTAEntities())
            {
                var model = db.Propertys.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    db.Propertys.Remove(model);
                    db.SaveChanges();
                }
                //return RedirectToAction("Index", "Product");    //Product為controller可略,會以目前controller為主
                return RedirectToAction("Index");
            }
        }


    }
}

foodfun/Areas/Admin/Views/Propertys/Create.cshtml
@model foodfun.Models.Propertys

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>新增商品屬性</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Propertys</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.property_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.property_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.property_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.property_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.property_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.property_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.add_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.add_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.add_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.property_value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.property_value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.property_value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
                @Html.ActionLink("返回", "Index", "Propertys", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}

foodfun/Areas/Admin/Views/Propertys/Edit.cshtml
@model foodfun.Models.Propertys

@{
    ViewBag.Title = "產品屬性修改";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>產品屬性修改</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Propertys</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.rowid)

        <div class="form-group">
            @Html.LabelFor(model => model.property_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.property_no, new { htmlAttributes = new { @class = "form-control" , disabled = "disabled"} })
                @Html.ValidationMessageFor(model => model.property_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.property_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.property_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.property_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.add_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.add_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.add_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.property_value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.property_value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.property_value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存異動" class="btn btn-default" />
                @Html.ActionLink("返回", "Index", "Propertys", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}

foodfun/Areas/Admin/Views/Propertys/Index.cshtml
@*@using PagedList.Mvc;
@using PagedList;*@


@model IEnumerable<foodfun.Models.Propertys>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>屬性設定</h2>

<html class="no-js" lang="">


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="assets/css/lib/datatable/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script>

</head>



<body>

    <div class="content">
        <div class="animated fadeIn">
            <div class="row">

                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">

                            @Html.ActionLink("新增記錄", "Create", "Propertys", null, new { @class = "btn btn-primary" })

                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <td> @Html.DisplayNameFor(model => model.rowid)</td>
                                        <td> @Html.DisplayNameFor(model => model.property_no)</td>
                                        <td> @Html.DisplayNameFor(model => model.property_name)</td>
                                        <td> @Html.DisplayNameFor(model => model.add_price)</td>
                                        <td> @Html.DisplayNameFor(model => model.property_value)</td>
                                        <td> @Html.DisplayNameFor(model => model.remark)</td>
                                       
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.rowid)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.property_no)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.property_name)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.add_price)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.property_value)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.remark)
                                            </td>


                                            <td>

                                                @Html.ActionLink("修改", "Edit", "Propertys", new { id = item.rowid }, new { @class = "btn btn-info" })

                                                @Html.ActionLink("刪除", "Delete", "Propertys", new { id = item.rowid }, new { @class = "btn btn-success", onclick = "return confirm('是否確定要刪除?')" })


                                            </td>
                                        </tr>
                                    }
                                    <tr>
                                        @*<td colspan="12">

                                            @Html.PagedListPager((IPagedList)Model, x => Url.Action("Index", new { page = x }))
                                                  轉成(IPagedList) 型別,  表頭table (roleList)   ,Url.Action  ( "list"指按下去產生list清單,之後看給Page多少


                                        </td>*@
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div><!-- .content -->


    <div class="clearfix"></div>



</body>
</html>